wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1651492073
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      2:
      - 1
      - 37
      - 41
      - 55
      3:
      - 13
      4: 3.8.5
      5: 0.12.15
      8:
      - 5
